### ISSUE TITLE
Installation instructions lead to 404

### ISSUE THREAD

**Issue by zakrywilson** [abudden/taghighlight-automirror#2]
The readme's link to the installation instructions (`http://www.cgtk.co.uk/taghighlight/install`) leads to a 404 on the CGTK page.

**Comment by zakrywilson** [comment]
Probably should link to this instead: https://www.cgtk.co.uk/vim-scripts/taghighlight/install-guide

**Comment by abudden** [comment]
Ah, good spot, thank you.  At the moment the mirroring of the master repository (which moved from bitbucket to heptapod when bitbucket stopped supporting mercurial) isn't working so this auto-mirror isn't up to date and I'm not sure how to fix it right now.

As a fix for this specific issue though, I've added a redirect on the website so the incorrect link now forwards to the correct link.
